config/routes.rb
Projectcamp::Application.routes.draw do
  devise_for :users

  root to: "bookings#public_index"
  resources :bookings 

  resources :pages, only: [:show, :index]

  get "sessions/login", to: "sessions#login", as: :login
  get "sessions/register", to: "sessions#register", as: :register
  
  
  match 'send_booking_ready_notification' => 'bookings#send_booking_ready_notification', :as => :send_booking_ready_notification, :method => :post 
  match 'close_booking' => 'bookings#close_booking', :as => :close_booking, :method => :post 
  match 'cancel_booking' => 'bookings#cancel_booking', :as => :cancel_booking, :method => :post 
  
  match 'refresh_booking_queue_row' => 'bookings#refresh_booking_queue_row', :as => :refresh_booking_queue_row, :method => :post 
  match 'refresh_public_booking_queue_row' => 'bookings#refresh_public_booking_queue_row', :as => :refresh_public_booking_queue_row, :method => :post 
  
  
  resources :projects   do
    resources :project_memberships 
    resources :deliverable_items 
  end
  
  resources :packages  do
    resources :deliverable_subcriptions  
  end
  
  resources :deliverables do
    resources :deliverable_components 
  end
  
  resources :deliverable_component_subcriptions do
    resources :drafts 
  end
  
  resources :job_requests 
  
=begin
  SETUP, Create User +  Office Role
=end

  match 'new_employee_creation' => "offices#new_employee_creation", :as => :new_employee_creation
  match 'create_employee' => "offices#create_employee" , :as => :create_employee, :method => :post 
  match 'show_role_for_employee/:employee_id' => "offices#show_role_for_employee" , :as => :show_role_for_employee
  match 'assign_role_for_employee' => "offices#assign_role_for_employee" , :as => :assign_role_for_employee, :method => :post

=begin
  Assigning project membership for employee
=end

  match 'assign_project_membership_role_for/:project_id' => "project_memberships#assign_project_membership_role_for",  :as => :assign_project_membership_role_for, :method => :post
  match 'finalize_membership_assignment' => "projects#finalize_membership_assignment",  :as => :finalize_membership_assignment, :method => :post 
  
=begin
  PRODUCTION MANAGEMENT 
=end

  match 'project_deliverable_items_production_overview/:project_id' => 'deliverable_items#project_deliverable_items_production_overview', :as => :project_deliverable_items_production_overview
  
  
  
=begin 
  JOB REQUEST FULFILLMENT  JOB_REQUEST_SOURCE[:assign_project_membership]
=end
  match 'task_based_project_membership_assignment/:job_request_id/for/:project_id' => "project_memberships#task_based_project_membership_assignment", :as => :task_based_project_membership_assignment
 
  
=begin 
  JOB REQUEST FULFILLMENT  JOB_REQUEST_SOURCE[:concept_planning]
=end
  match 'project_based_concept_planning_fulfillment/:project_id' => "projects#project_based_concept_planning_fulfillment", :as => :project_based_concept_planning_fulfillment
  match 'concept_planning_fulfillment/:job_request_id/for/:project_id' => "projects#concept_planning_fulfillment", :as => :concept_planning_fulfillment
  match 'update_project_concept/:project_id' => "projects#update_project_concept", :as => :update_project_concept, :method => :post 
  match 'finalize_concept' => 'projects#finalize_concept', :as => :finalize_concept, :method => :post 
  
=begin 
  JOB REQUEST FULFILLMENT  JOB_REQUEST_SOURCE[:shoot]
=end
  match 'project_based_shoot_finalization/:project_id' => "projects#project_based_shoot_finalization", :as => :project_based_shoot_finalization
  match 'shoot_finalization/:job_request_id/for/:project_id' => "projects#shoot_finalization", :as => :shoot_finalization
  match 'update_shoot_data/:project_id' => "projects#update_shoot_data", :as => :update_shoot_data, :method => :post
  match 'finalize_shoot_data' => 'projects#finalize_shoot_data', :as => :finalize_shoot_data, :method => :post 
  
=begin
  JOB REQUEST: Start Production
=end
  match 'task_based_deliverable_items_progress/:project_id' => "deliverable_items#task_based_deliverable_items_progress", :as => :task_based_deliverable_items_progress
  match 'task_based_draft_creation_for_component/:deliverable_component_subcription_id' => "drafts#task_based_draft_creation_for_component", :as => :task_based_draft_creation_for_component
  
  match 'task_based_production_team_assignment/:job_request_id/for/:project_id' => 'drafts#task_based_production_team_assignment', :as => :task_based_production_team_assignment
  
=begin
  DRAFT PRODUCTION, not from task 
=end
  match 'production_team_assignment/:draft_id' => 'drafts#production_team_assignment', :as => :production_team_assignment 
  match 'execute_production_team_assignment/:draft_id' => 'drafts#execute_production_team_assignment', :as => :execute_production_team_assignment, :method => :post 
  match 'finalize_production_team_assignment' => 'drafts#finalize_production_team_assignment', :as =>  :finalize_production_team_assignment, :method => :post 
  match 'internal_qc_deadline_assignment/:draft_id' => "drafts#internal_qc_deadline_assignment", :as => :internal_qc_deadline_assignment
  match 'execute_internal_qc_deadline_assignment/:draft_id' => 'drafts#execute_internal_qc_deadline_assignment', :as => :execute_internal_qc_deadline_assignment, :method => :post 
  
end

app/models/office.rb
class Office < ActiveRecord::Base
  attr_accessible :name
  has_many :users 
  has_many :bookings 
  has_many :deliveries 
  has_many :seat_categories 
  
  after_create :create_channel_code
  
  
  
  def create_channel_code
    creation_time = self.created_at
    channel_code = ""
    channel_code << creation_time.year.to_s + creation_time.month.to_s + creation_time.day.to_s 
    channel_code << self.id.to_s
    self.channel_code = channel_code.to_i.to_s(16)
    self.save 
  end
  
  def confirmation_sms_text( booking )
    sms_string = ""
    sms_string << "[#{self.name}]-Confirmation\n"  
    sms_string << "#{booking.name}\n" 
    sms_string << "Code: #{booking.booking_code}\n" 
    sms_string << "#{booking.seat_category.name}\n" 
    people_enumerator = ''
    if booking.number_of_people > 1 
      people_enumerator = 'people'
    else
      people_enumerator = 'person'
    end
    
    sms_string << "#{booking.number_of_people} #{people_enumerator}" 
  end
  
  def seat_ready_sms_text(booking)
    sms_string = ""
    sms_string << "[#{self.name}]-Ready\n"  
    sms_string << "#{booking.name}\n" 
    sms_string << "Code: #{booking.booking_code}\n" 
    sms_string << "#{booking.seat_category.name}\n" 
    people_enumerator = ''
    if booking.number_of_people > 1 
      people_enumerator = 'people'
    else
      people_enumerator = 'person'
    end
    
    sms_string << "#{booking.number_of_people} #{people_enumerator}"
  end
end

app/controllers/offices_controller.rb
class OfficesController < ApplicationController
  def new_employee_creation
    @new_employee = User.new 
    @employees = User.order("created_at DESC")
    
    add_breadcrumb "Manpower Management", 'new_employee_creation_url'
  end
  
  def create_employee
    @new_object = User.create_basic_user(current_user,  params[:user] )   
    
    
    # what's gonna happen if it is jquery AJAX ? 
    
    # if not @new_employee.nil? and @new_employee.valid?
    #   flash[:notice] = "The employee '#{@new_employee.email}' has been created." 
    #   redirect_to new_employee_creation_url
    #   return 
    # else
    #   @employees = current_office.users
    #   @new_employee = User.new 
    #   flash[:error] = []
    #   if params[:user][:email].nil? or params[:user][:email].length == 0 
    #     flash[:error] << "Email has to be present"
    #   end
    #   
    #   if User.find_by_email(params[:user][:email]).nil?
    #     flash[:error] << "There is duplicate email"
    #   end
    #     
    #   render :file => "offices/new_employee_creation"
    # end
  end
  
  def show_role_for_employee
    @employee = User.find_by_id params[:employee_id]
    @roles = Role.find(:all, :order => "created_at ASC")
    
    add_breadcrumb "Manpower Management", 'new_employee_creation_url'
    set_breadcrumb_for @employee, 'show_role_for_employee_url' + "(#{@employee.id})", 
                " Role Assignment for #{@employee.name} "
                
                
  end
  
  def assign_role_for_employee
    @decision = params[:membership_decision].to_i
    @role = Role.find_by_id params[:membership_provider]
    @employee = User.find_by_id params[:membership_consumer] 
  
    if @decision == TRUE_CHECK
      puts "**** WE are calling add role "
      # @employee.add_role(@role, @office, current_user)
      @employee.add_role( @role,  current_user)
    elsif @decision == FALSE_CHECK
      puts "((((( We are calling remove role)))))"
      @employee.remove_role(@role,  current_user)
    end
    @employee.reload 
    
    respond_to do |format|
      format.html {  redirect_to root_url }
      format.js
    end
  end
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/views/offices/_employee_list_entry.html.erb
<tr id="employee_list_entry-<%= object.id %>"> 
  <td>
    <%= link_to object.name , show_role_for_employee_url(object) %>
  </td>
  <td>
    <% if object.has_role?(:admin)%>
      <span class="label green">Yes</span>
    <% else %>
      <span class="label">No</span>
    <% end %>
  </td>
  <td>
    <% if object.has_role?(:head_project_manager)%>
      <span class="label green">Yes</span>
    <% else %>
      <span class="label">No</span>
    <% end %>
  </td>
  <td>
    <% if object.has_role?(:employee)%>
      <span class="label green">Yes</span>
    <% else %>
      <span class="label">No</span>
    <% end %>
  </td> 
</tr>

app/views/offices/_new_employee_form.html.erb
<%= simple_form_for( new_object, :url => url,
      :method => :post , 
      :html => {:class => "form-horizontal prevent_double_submit ajax-form   no_content_form",
        :id => "new_object"}) do |f| %>

  <%= f.input :name , :input_html => {:class => "input-xlarge span5"}, 
  :label => "Name" %>

  <%= f.input :email , :input_html => {:class => "input-xlarge span5"}, 
  :label => "Email" %>

  <div class="form-actions">
    <%= f.button :submit , :class => "btn btn-primary", :value=> "Create Employee" %>
  </div>
<% end %>

app/views/offices/_role_entry.html.erb
<tr id="role_entry_<%= role.id %>">
  <td>
    <%= role.name %>
  </td>
  <td>
    <% checkbox_value = employee.has_role?(role.name.underscore.to_sym) %>

    <%= check_box_tag 'is_checked', get_checkbox_value(checkbox_value )   , 
        checkbox_value, :class => 'checkbox_tracker', 
        :id => "provider_#{role.id}-consumer_#{employee.id}" %> OK
  </td>
</tr>

app/views/offices/assign_role_for_employee.js.erb
$(document).ready(function(){

  <% new_row = escape_javascript(  render :partial => "offices/role_entry", :locals => {
            :role => @role,
            :employee => @employee
          }) %>
          
  $("#role_entry_<%= @role.id %>").replaceWith('<%= new_row %>');
});

app/views/offices/create_employee.js.erb
$(document).ready(function(){
  var $form = $("#new_object");  
  <% new_form = escape_javascript(  render :partial => "offices/new_employee_form", :locals => {
            :new_object => @new_object,
            :url => create_employee_url
          }) %>
  
  //  hide showLoading 
  $form.hideLoading();  
  $form.replaceWith('<%= new_form %>');  
  var $form = $("#new_object");  
  
  // show the alert (either success or fail)
  var $form_opener = $("#new_object_opener");
   
  <% if @new_object.persisted? %>
  // show notification that it is persisted
    <% alert = escape_javascript(render :partial => "layouts/alert", :locals => {
      :success => true , 
      :text => "#{@new_object.name} is successfully created."
    }) %>
  //  hide the form 
    $form.hide(); 
    $form.clearForm(); 
  // add the entry into the table 
  
    <% new_row = escape_javascript(  render :partial => "offices/employee_list_entry", :locals => { 
              :object => @new_object
            }) %>
          
    $("#object_list").prepend('<%= new_row %>');
  
  
  <% else %>
    <% alert = escape_javascript(render :partial => "layouts/alert", :locals => {
      :success => false , 
      :text => "New Employee Creation Failed."
    }) %> 
    $form.show(); 
  <% end %>
  
  if( $("#alert").length == 0 ){
    $("#new_object_opener").after('<%= alert %>');
  }else{
    $("#alert").replaceWith('<%= alert %>');
  }
  
  
  
});

app/views/offices/new_employee_creation.html.erb
<div class="padded">
  
  <%= render :partial => "layouts/new_object_opener", :locals => {
    :text => "New Employee"
  } %>
  
  <% if @employees.length == 0 %>
    <%= render :partial => "layouts/no_object_list", :locals => {
      :objects => "packages",
      :single_object => "package" ,
      :subject => "company"
    } %>
  <% end %>
  
   
  <%= render :partial => "offices/new_employee_form", :locals => {
    :new_object => @new_employee,
    :url => create_employee_url  
  }%>
 
  
  
  
  
  
  <table class="table table-bordered table-striped table-header" id="object_list">
    <thead>
      <tr>
        <th>Name</th>
        <th>Admin</th>
        <th>Head PM</th>
        <th>Employee</th> 
      </tr>
    </thead>
    <tbody id="employee_list">
      <% @employees.each do |employee| %>
        <%= render :partial => "offices/employee_list_entry", :locals => {
          :object => employee 
        }%>
        
      <% end %> 
    </tbody>
  </table>
</div>

app/views/offices/show_role_for_employee.html.erb
<div class="padded">
  <table class="table table-bordered table-striped table-header">
    <thead>
      <tr>
        <th>Role</th>
        <th>Is Assigned?</th>
      </tr>
    </thead>
    <tbody>
      
      
      <% USER_ROLE.each do |key,value| %>
        <% role = Role.find_by_name value %>
        <%= render :partial => 'offices/role_entry', :locals => {
          :role => role, 
          :employee => @employee
        }%>
        
        
      <% end %>
       
    </tbody>
  </table>
</div>

<div class=" hidden" id="checkbox_form_wrapper">
  <%= form_for Assignment.new, :url => assign_role_for_employee_url,  :method => :post   do |f| %>
    <%= hidden_field_tag 'membership_provider' , ''  %>
    <%= hidden_field_tag 'membership_consumer', '' %>
    <%= hidden_field_tag 'membership_decision', '' %>
  <% end %>
</div>