config/routes.rb
Projectcamp::Application.routes.draw do
  devise_for :users

  root to: "bookings#public_index"
  resources :bookings 

  resources :pages, only: [:show, :index]

  get "sessions/login", to: "sessions#login", as: :login
  get "sessions/register", to: "sessions#register", as: :register
  
  
  match 'send_booking_ready_notification' => 'bookings#send_booking_ready_notification', :as => :send_booking_ready_notification, :method => :post 
  match 'close_booking' => 'bookings#close_booking', :as => :close_booking, :method => :post 
  match 'cancel_booking' => 'bookings#cancel_booking', :as => :cancel_booking, :method => :post 
  
  match 'refresh_booking_queue_row' => 'bookings#refresh_booking_queue_row', :as => :refresh_booking_queue_row, :method => :post 
  match 'refresh_public_booking_queue_row' => 'bookings#refresh_public_booking_queue_row', :as => :refresh_public_booking_queue_row, :method => :post 
  
  
  resources :projects   do
    resources :project_memberships 
    resources :deliverable_items 
  end
  
  resources :packages  do
    resources :deliverable_subcriptions  
  end
  
  resources :deliverables do
    resources :deliverable_components 
  end
  
  resources :deliverable_component_subcriptions do
    resources :drafts 
  end
  
  resources :job_requests 
  
=begin
  SETUP, Create User +  Office Role
=end

  match 'new_employee_creation' => "offices#new_employee_creation", :as => :new_employee_creation
  match 'create_employee' => "offices#create_employee" , :as => :create_employee, :method => :post 
  match 'show_role_for_employee/:employee_id' => "offices#show_role_for_employee" , :as => :show_role_for_employee
  match 'assign_role_for_employee' => "offices#assign_role_for_employee" , :as => :assign_role_for_employee, :method => :post

=begin
  Assigning project membership for employee
=end

  match 'assign_project_membership_role_for/:project_id' => "project_memberships#assign_project_membership_role_for",  :as => :assign_project_membership_role_for, :method => :post
  match 'finalize_membership_assignment' => "projects#finalize_membership_assignment",  :as => :finalize_membership_assignment, :method => :post 
  
=begin
  PRODUCTION MANAGEMENT 
=end

  match 'project_deliverable_items_production_overview/:project_id' => 'deliverable_items#project_deliverable_items_production_overview', :as => :project_deliverable_items_production_overview
  
  
  
=begin 
  JOB REQUEST FULFILLMENT  JOB_REQUEST_SOURCE[:assign_project_membership]
=end
  match 'task_based_project_membership_assignment/:job_request_id/for/:project_id' => "project_memberships#task_based_project_membership_assignment", :as => :task_based_project_membership_assignment
 
  
=begin 
  JOB REQUEST FULFILLMENT  JOB_REQUEST_SOURCE[:concept_planning]
=end
  match 'project_based_concept_planning_fulfillment/:project_id' => "projects#project_based_concept_planning_fulfillment", :as => :project_based_concept_planning_fulfillment
  match 'concept_planning_fulfillment/:job_request_id/for/:project_id' => "projects#concept_planning_fulfillment", :as => :concept_planning_fulfillment
  match 'update_project_concept/:project_id' => "projects#update_project_concept", :as => :update_project_concept, :method => :post 
  match 'finalize_concept' => 'projects#finalize_concept', :as => :finalize_concept, :method => :post 
  
=begin 
  JOB REQUEST FULFILLMENT  JOB_REQUEST_SOURCE[:shoot]
=end
  match 'project_based_shoot_finalization/:project_id' => "projects#project_based_shoot_finalization", :as => :project_based_shoot_finalization
  match 'shoot_finalization/:job_request_id/for/:project_id' => "projects#shoot_finalization", :as => :shoot_finalization
  match 'update_shoot_data/:project_id' => "projects#update_shoot_data", :as => :update_shoot_data, :method => :post
  match 'finalize_shoot_data' => 'projects#finalize_shoot_data', :as => :finalize_shoot_data, :method => :post 
  
=begin
  JOB REQUEST: Start Production
=end
  match 'task_based_deliverable_items_progress/:project_id' => "deliverable_items#task_based_deliverable_items_progress", :as => :task_based_deliverable_items_progress
  match 'task_based_draft_creation_for_component/:deliverable_component_subcription_id' => "drafts#task_based_draft_creation_for_component", :as => :task_based_draft_creation_for_component
  
  match 'task_based_production_team_assignment/:job_request_id/for/:project_id' => 'drafts#task_based_production_team_assignment', :as => :task_based_production_team_assignment
  
=begin
  DRAFT PRODUCTION, not from task 
=end
  match 'production_team_assignment/:draft_id' => 'drafts#production_team_assignment', :as => :production_team_assignment 
  match 'execute_production_team_assignment/:draft_id' => 'drafts#execute_production_team_assignment', :as => :execute_production_team_assignment, :method => :post 
  match 'finalize_production_team_assignment' => 'drafts#finalize_production_team_assignment', :as =>  :finalize_production_team_assignment, :method => :post 
  match 'internal_qc_deadline_assignment/:draft_id' => "drafts#internal_qc_deadline_assignment", :as => :internal_qc_deadline_assignment
  match 'execute_internal_qc_deadline_assignment/:draft_id' => 'drafts#execute_internal_qc_deadline_assignment', :as => :execute_internal_qc_deadline_assignment, :method => :post 
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index 
    @new_project = Project.new 
    @projects = Project.active_projects
    
    add_breadcrumb "Project Management", 'projects_url'
  end
  
   
  def create 
    @new_object =  Project.create_object( current_user, params[:project])  
  end
  
  def show
    @project = Project.find_by_id(params[:id])
    @deliverable_items = @project.active_deliverable_items 
    
    setup_project_role
    
    add_breadcrumb "Project Management", 'projects_url'
    set_breadcrumb_for @project, 'project_url' + "(#{@project.id})", 
          "Project Management"
    
  end
  
  def update
    @project = Project.find_by_id params[:id]
    @project.update_with_attributes( current_user , params[:project] )
    @has_no_errors  = @project.errors.messages.length == 0 
    puts "The value of has no errors: #{@has_no_errors}"
    if @project.errors.messages.length != 0 
      puts "The project contains many errors\n"*5
      puts "The errors: "
      puts "The length : #{@project.errors.messages.length}"
      @project.errors.messages.each do |key, value|
        puts "#{value}"
      end
    else
      puts "The project doesn't have any errors\n"*5
    end
  end
  
  def finalize_membership_assignment
    @project = Project.find_by_id params[:entity_id]
    
    @project.finalize_project_membership_assignment(current_user)
  end
  
  
=begin
  JOB REQUEST FULFILLMENT  JOB_REQUEST_SOURCE[:concept_planning]
=end

  def project_based_concept_planning_fulfillment
    @project = Project.find_by_id params[:project_id] 
    
    add_breadcrumb "Project Management", 'projects_url'  
    set_breadcrumb_for @project, 'concept_planning_fulfillment_url' + "(#{@project.id})", 
          "Concept Planning"
          
    # render :file => "projects/job_requests/concept_planning/concept_planning_fulfillment"
  end
  
  def concept_planning_fulfillment
    @project = Project.find_by_id params[:project_id]  
    
    add_breadcrumb "Task Management", 'job_requests_url'  
    set_breadcrumb_for @project, 'concept_planning_fulfillment_url' + "(#{@project.id})", 
          "Concept Planning"
          
    render :file => "projects/job_requests/concept_planning/concept_planning_fulfillment"
  end
  
  def update_project_concept
    @project = Project.find_by_id params[:project_id]
    @project.update_project_concept(current_user, params[:project][:concept])
    @project.reload 
    @object = @project 
     
  
    render :file => "projects/job_requests/concept_planning/update_project_concept"
  end
  
  def finalize_concept
    @project = Project.find_by_id params[:entity_id] 
    @project.finalize_concept(current_user)
    
    render :file => "projects/job_requests/concept_planning/finalize_concept" 
  end
  
  
  
=begin
  JOB REQUEST FULFILLMENT  JOB_REQUEST_SOURCE[:shoot]
=end

  def project_based_shoot_finalization
    @project = Project.find_by_id params[:project_id] 

    add_breadcrumb "Project Management", 'projects_url'  
    set_breadcrumb_for @project, 'project_based_shoot_finalization_url' + "(#{@project.id})", 
          "Shoot Data Planning"

    # render :file => "projects/job_requests/concept_planning/concept_planning_fulfillment"
  end

  def shoot_finalization
    @project = Project.find_by_id params[:project_id]  

    add_breadcrumb "Task Management", 'job_requests_url'  
    set_breadcrumb_for @project, 'shoot_finalization_url' + "(#{@project.id})", 
          "Shoot Finalization"

    render :file => "projects/job_requests/shoot/shoot_finalization"
  end

  def update_shoot_data
    @project = Project.find_by_id params[:project_id]
    @project.update_project_shoot_data(current_user, params[:project][:shoot_data])
    @project.reload 
    @object = @project 
 


    render :file => "projects/job_requests/shoot/update_shoot_data"
  end
  
  def finalize_shoot_data
    @project = Project.find_by_id params[:entity_id] 
    @project.finalize_shoot_data(current_user)
    
    render :file => "projects/job_requests/shoot/finalize_shoot_data" 
  end
  
  protected 
  
  def setup_project_role
    @main_crew_project_role = ProjectRole.find_by_name PROJECT_ROLE[:main_crew]
    @crew_project_role = ProjectRole.find_by_name PROJECT_ROLE[:crew]
    @pm_project_role = ProjectRole.find_by_name PROJECT_ROLE[:project_manager]
    @ae_project_role = ProjectRole.find_by_name PROJECT_ROLE[:account_executive] 
    @qc_project_role = ProjectRole.find_by_name PROJECT_ROLE[:quality_control]
  end
  
  
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_new_object_form.html.erb
<%= simple_form_for( new_object, :url => url,
      :method => :post , 
      :html => {:class => "form-horizontal prevent_double_submit ajax-form   no_content_form",
        :id => "new_object"}) do |f| %>

  <%= f.input :title  , :input_html => {:class => "input-xlarge span5"}, 
  :label => "Title" %>
  
  <%= f.input :package_id, :hint => "Select Package", :label => "Package" do %>
     <%= f.select :package_id, 
         Package.all_selectable_packages %>
   <% end %>
   
   <hr />

  <%= f.input :external_deadline , :as => :string, 
    :input_html => {:class => "input-xlarge datepicker span5", :rows => 5,
      :value => format_date_from_datetime( new_object.external_deadline)}, 
    :label => "External Deadline", :hint => "(format: dd/mm/yyyy)"   %>
    
  

  <div class="form-actions">
    <%= f.button :submit , :class => "btn btn-primary", :value=> "Create Project" %>
  </div>
<% end %>

app/views/projects/_object_list_entry.html.erb
<tr id="object_list_entry-<%= object.id %>"> 
  <!-- Title -->
  <td>
    <%=  link_to  object.title , project_url( object )   %>
  </td>
  
  <!-- External Deadline -->
  <td> 
    <%= format_date_from_datetime( object.external_deadline )  %>
  </td>
  
  <!-- Deliverables -->
  <td> 
    <%= link_to  project_deliverable_items_url(object) do %>
      <span class="badge blue rounded"><%= object.deliverable_items.count %></span> 
    <% end %> 
  </td>
  
  <!-- Project Memberships -->
  <td> 
    
    <%= link_to project_project_memberships_url(object)  do %>
      <% if object.is_membership_assignment_finalized and object.is_core_project_member_complete? %>
        <span class="label green">Complete</span>
      <% else %>
        <span class="label orange">Pending</span> 
      <% end %>
    <% end %>
    
    <%= link_to project_project_memberships_url(object)  do %>
      <span class="badge blue rounded"><%= object.users.count %></span> 
    <% end %>
    
  </td>
  <td> 
    
    <%= link_to project_based_concept_planning_fulfillment_url(object)  do %>
      <% if object.is_concept_finalized == true %>
        <span class="label green">Done</span>
      <% else %>
        <% if not object.concept.nil? and not object.concept.length == 0  %>
          <span class='label orange'>In Progress</span>
        <% else %>
          <span class='label red'>Not Started</span>
        <% end %>
      <% end %>
    <% end %> 
    
  </td>
  <td> 
    
    
    <%= link_to project_based_shoot_finalization_url(object)  do %>
      <% if object.is_shoot_finalized == true %>
        <span class="label green">Done</span>
      <% else %>
        <% if not object.shoot_data.nil? and not object.shoot_data.length == 0  %>
          <span class='label orange'>In Progress</span>
        <% else %>
          <span class='label red'>Not Started</span>
        <% end %>
      <% end %>
    <% end %>
    
  </td>
  <td> 
    <span class='bold'>Album</span> 
    <ul class="deliverable_summary">
      <li> 
        Cover <span class='label green'>done</span>
      </li>
      <li>
        Packaging <span class='label orange'>Pending</span>
      </li>
      <li>
        Content <span class='label red'>NA</span>
      </li>
    </ul>
    
    <span class='bold'>Canvas</span>  
    <ul class="deliverable_summary">
      <li> 
        Frame <span class='label green'>done</span>
      </li>
      <li>
        Image
      </li> 
    </ul>
  </td>
  <td> 
    <%= format_date_from_datetime( object.external_deadline )  %>
  </td>
  
</tr>

app/views/projects/create.js.erb
$(document).ready(function(){
  var $form = $("#new_object");  
  <% new_form = escape_javascript(  render :partial => "projects/new_object_form", :locals => {
            :new_object => @new_object,
            :url => projects_url 
          }) %>
  
  //  hide showLoading 
  $form.hideLoading();  
  $form.replaceWith('<%= new_form %>');  
  var $form = $("#new_object");  
  
  // show the alert (either success or fail)
  var $form_opener = $("#new_object_opener");
   
  <% if @new_object.persisted? %>
  // show notification that it is persisted
    <% alert = escape_javascript(render :partial => "layouts/alert", :locals => {
      :success => true , 
      :text => "#{@new_object.title} is successfully created."
    }) %>
  //  hide the form 
    $form.hide(); 
    $form.clearForm(); 
  // add the entry into the table 
  
    <% new_row = escape_javascript(  render :partial => "projects/object_list_entry", :locals => { 
              :object => @new_object
            }) %>
          
    $("#object_list").prepend('<%= new_row %>');
  
    // show the table (if it is the first viewable object)
    $("#object_list").removeClass("<%= HIDE_TABLE %>")
    $("#no_object_list").remove();
  
  <% else %>
    <% alert = escape_javascript(render :partial => "layouts/alert", :locals => {
      :success => false , 
      :text => "Project Creation Failed."
    }) %> 
    $form.show(); 
  <% end %>
  
  if( $("#alert").length == 0 ){
    $("#new_object_opener").after('<%= alert %>');
  }else{
    $("#alert").replaceWith('<%= alert %>');
  }
  
  
  
  $(".datepicker").datepicker({
    format: 'dd/mm/yyyy',
    autoclose : true 
  });
  
   
  
  
});

app/views/projects/index.html.erb
<div class="padded">
  
  
  <% if  current_user.has_role?(:head_project_manager)%>
    <%= render :partial => "layouts/new_object_opener", :locals => {
      :text => "New Project"
    } %>
  <% end %>
  
  
   
  <% if @projects.length == 0 %>
    <%= render :partial => "layouts/no_object_list", :locals => {
      :objects => "active projects",
      :single_object => "project" , 
      :subject => "company"
    } %>
  <% end %>
   
   
  <% if  current_user.has_role?(:head_project_manager)%>
    <%= render :partial => "projects/new_object_form", :locals => {
      :new_object => @new_project,
      :url => projects_url  
    }%>
  <% end %>
 
 
 
  
  
  
    
    <table class="table table-bordered table-striped table-header <%= show_table?( @projects )%>" id="object_list">
      <thead>
        <tr>
          <th>Title</th>
          <th>Deadline</th>
          <th>Deliverables</th>
          <th>Membership</th>
          <th>Concept</th> 
          <th>Shoot Data</th> 
          <th>Production</th>
          <th>Post Production</th>
        </tr>
      </thead>
      <tbody id="package_list">
        <% @projects.each do |project| %>
          <%= render :partial => "projects/object_list_entry", :locals => {
            :object => project 
          }%>
        
        <% end %> 
      </tbody>
    </table>
</div>