config/routes.rb
Projectcamp::Application.routes.draw do
  devise_for :users

  root to: "bookings#public_index"
  resources :bookings 

  resources :pages, only: [:show, :index]

  get "sessions/login", to: "sessions#login", as: :login
  get "sessions/register", to: "sessions#register", as: :register
  
  
  match 'send_booking_ready_notification' => 'bookings#send_booking_ready_notification', :as => :send_booking_ready_notification, :method => :post 
  match 'close_booking' => 'bookings#close_booking', :as => :close_booking, :method => :post 
  match 'cancel_booking' => 'bookings#cancel_booking', :as => :cancel_booking, :method => :post 
  
  match 'refresh_booking_queue_row' => 'bookings#refresh_booking_queue_row', :as => :refresh_booking_queue_row, :method => :post 
  match 'refresh_public_booking_queue_row' => 'bookings#refresh_public_booking_queue_row', :as => :refresh_public_booking_queue_row, :method => :post 
  
  
  resources :projects   do
    resources :project_memberships 
    resources :deliverable_items 
  end
  
  resources :packages  do
    resources :deliverable_subcriptions  
  end
  
  resources :deliverables do
    resources :deliverable_components 
  end
  
  resources :deliverable_component_subcriptions do
    resources :drafts 
  end
  
  resources :job_requests 
  
=begin
  SETUP, Create User +  Office Role
=end

  match 'new_employee_creation' => "offices#new_employee_creation", :as => :new_employee_creation
  match 'create_employee' => "offices#create_employee" , :as => :create_employee, :method => :post 
  match 'show_role_for_employee/:employee_id' => "offices#show_role_for_employee" , :as => :show_role_for_employee
  match 'assign_role_for_employee' => "offices#assign_role_for_employee" , :as => :assign_role_for_employee, :method => :post

=begin
  Assigning project membership for employee
=end

  match 'assign_project_membership_role_for/:project_id' => "project_memberships#assign_project_membership_role_for",  :as => :assign_project_membership_role_for, :method => :post
  match 'finalize_membership_assignment' => "projects#finalize_membership_assignment",  :as => :finalize_membership_assignment, :method => :post 
  
=begin
  PRODUCTION MANAGEMENT 
=end

  match 'project_deliverable_items_production_overview/:project_id' => 'deliverable_items#project_deliverable_items_production_overview', :as => :project_deliverable_items_production_overview
  
  
  
=begin 
  JOB REQUEST FULFILLMENT  JOB_REQUEST_SOURCE[:assign_project_membership]
=end
  match 'task_based_project_membership_assignment/:job_request_id/for/:project_id' => "project_memberships#task_based_project_membership_assignment", :as => :task_based_project_membership_assignment
 
  
=begin 
  JOB REQUEST FULFILLMENT  JOB_REQUEST_SOURCE[:concept_planning]
=end
  match 'project_based_concept_planning_fulfillment/:project_id' => "projects#project_based_concept_planning_fulfillment", :as => :project_based_concept_planning_fulfillment
  match 'concept_planning_fulfillment/:job_request_id/for/:project_id' => "projects#concept_planning_fulfillment", :as => :concept_planning_fulfillment
  match 'update_project_concept/:project_id' => "projects#update_project_concept", :as => :update_project_concept, :method => :post 
  match 'finalize_concept' => 'projects#finalize_concept', :as => :finalize_concept, :method => :post 
  
=begin 
  JOB REQUEST FULFILLMENT  JOB_REQUEST_SOURCE[:shoot]
=end
  match 'project_based_shoot_finalization/:project_id' => "projects#project_based_shoot_finalization", :as => :project_based_shoot_finalization
  match 'shoot_finalization/:job_request_id/for/:project_id' => "projects#shoot_finalization", :as => :shoot_finalization
  match 'update_shoot_data/:project_id' => "projects#update_shoot_data", :as => :update_shoot_data, :method => :post
  match 'finalize_shoot_data' => 'projects#finalize_shoot_data', :as => :finalize_shoot_data, :method => :post 
  
=begin
  JOB REQUEST: Start Production
=end
  match 'task_based_deliverable_items_progress/:project_id' => "deliverable_items#task_based_deliverable_items_progress", :as => :task_based_deliverable_items_progress
  match 'task_based_draft_creation_for_component/:deliverable_component_subcription_id' => "drafts#task_based_draft_creation_for_component", :as => :task_based_draft_creation_for_component
  
  match 'task_based_production_team_assignment/:job_request_id/for/:project_id' => 'drafts#task_based_production_team_assignment', :as => :task_based_production_team_assignment
  
=begin
  DRAFT PRODUCTION, not from task 
=end
  match 'production_team_assignment/:draft_id' => 'drafts#production_team_assignment', :as => :production_team_assignment 
  match 'execute_production_team_assignment/:draft_id' => 'drafts#execute_production_team_assignment', :as => :execute_production_team_assignment, :method => :post 
  match 'finalize_production_team_assignment' => 'drafts#finalize_production_team_assignment', :as =>  :finalize_production_team_assignment, :method => :post 
  match 'internal_qc_deadline_assignment/:draft_id' => "drafts#internal_qc_deadline_assignment", :as => :internal_qc_deadline_assignment
  match 'execute_internal_qc_deadline_assignment/:draft_id' => 'drafts#execute_internal_qc_deadline_assignment', :as => :execute_internal_qc_deadline_assignment, :method => :post 
  
end

app/controllers/job_requests_controller.rb
class JobRequestsController < ApplicationController
  def index
    @job_requests = current_user.active_job_requests.joins(:project)
    
    add_breadcrumb "Task Management", 'job_requests_url'
  end
end

app/helpers/job_requests_helper.rb
module JobRequestsHelper
end

app/views/bookings/job_requests/concept_planning/_concept_finalized.html.erb
<div class="alert alert-success finalize">
  <i class="icon-ok-sign"></i> Finalized
</div>

app/views/bookings/job_requests/concept_planning/_display.html.erb
<div class="row " id="display_content"> 
  <div style="line-height: 24px;" class="span8 content_display"> 
    <%= project.concept.html_safe  %> 
  </div>
</div>

app/views/bookings/job_requests/concept_planning/_finalize_concept.html.erb
<%= simple_form_for( project, :url => finalize_concept_url,
      :method => :post , 
      :html => {:class => "form-horizontal prevent_double_submit ajax-form" ,
        :id => "finalizer"}) do |f| %>

 
        <%= hidden_field_tag 'entity_id' , project.id  %>
  <div class="form-actions">
    <%= f.button :submit , :class => "btn green", :value=> "Finalize Project Concept" %>
  </div>
<% end %>

app/views/bookings/job_requests/concept_planning/_object_form.html.erb
<%= simple_form_for( object, :url => url,
      :method => :post , 
      :html => {:class => "form-horizontal prevent_double_submit ajax-form   no_content_form",
        :id => "object_form"}) do |f| %>

  <%= f.input :concept  , :input_html => {:class => "input-xlarge span5 wysihtml5_textarea" , :rows => 5 }, 
  :label => "Concept" %>
   
   
   <hr /> 
  <div class="form-actions">
    <%= f.button :submit , :class => "btn btn-primary", :value=> "Create Project Concept" %>
  </div>
<% end %>

app/views/bookings/job_requests/concept_planning/concept_planning_fulfillment.html.erb
<% content_for :additional_js do %>
  <%= javascript_include_tag "project_summary", "wysihtml5-0.3.0_rc2.min", "bootstrap-wysihtml5-0.0.2.min" %>
  <script type="text/javascript">
    $(document).ready(function(){
      $('.wysihtml5_textarea').wysihtml5({
      	"html": false, //Button which allows you to edit the generated HTML. Default false
      	"image": false //Button to insert an image. Default true
      }); 
    });
  </script>
<% end %>

<% content_for :additional_css do %>
  <%= stylesheet_link_tag "bootstrap-wysihtml5-0.0.2" %>
<% end %>






<div class="padded">
  
  
  <% if @project.is_concept_finalized == true %>
     <%= render :partial => "projects/job_requests/concept_planning/concept_finalized", :locals => {
       :project => @project 
     }%>
   <% else %>
     <%= render :partial => "projects/job_requests/concept_planning/finalize_concept", :locals => {
       :project => @project 
     }%>
   <% end %>
   
  <% if  current_user.has_project_role_symbol?(@project, :main_crew )%>
    <%= render :partial => "layouts/new_object_opener", :locals => {
      :text => "Edit Concept"
    } %>
  <% end %>
  
  
  
 
  
  
   
  <% if @project.concept.nil? or @project.concept.length == 0 %>
    <%= render :partial => "layouts/no_object_list", :locals => {
      :objects => "concept ",
      :single_object => "concept" , 
      :subject => "project \"#{@project.title}\""
    } %>
  <% else %>
    <%= render :partial => "projects/job_requests/concept_planning/display", :locals => {
      :project => @project 
    } %>
  <% end %>
   
   
  <% if  current_user.has_project_role_symbol?(@project, :main_crew)%>
    <%= render :partial => "projects/job_requests/concept_planning/object_form", :locals => {
      :object => @project,
      :url => update_project_concept_url(@project )  
    }%>
  <% end %>
   
</div>

app/views/bookings/job_requests/concept_planning/finalize_concept.js.erb
$(document).ready(function(){
  
  
  $("#finalizer").hideLoading();
  <% if @project.is_concept_finalized == true %>
    <% new_notification = escape_javascript(render :partial => "projects/job_requests/concept_planning/concept_finalized", 
      :locals => {
      :project => @project 
    }) %>
    
    $("#finalizer").replaceWith('<%= new_notification %>' );
  <% else %>
   
    <% new_form = escape_javascript(render :partial => "projects/job_requests/concept_planning/finalize_concept", 
      :locals => {
      :project => @project 
    }) %>
    
    $("#finalizer").replaceWith('<%= new_form %>' );
  <% end %>
  
});

app/views/bookings/job_requests/concept_planning/update_project_concept.js.erb
$(document).ready(function(){
  var $form = $("#object_form");  
  <% new_form = escape_javascript( render :partial => "projects/job_requests/concept_planning/object_form", :locals => {
    :object => @object,
    :url => update_project_concept_url(@object )  
  }) %>
  
  //  hide showLoading 
  $form.hideLoading();  
  $form.replaceWith('<%= new_form %>');  
  var $form = $("#object_form");  
  
  var $alert = $("#alert"); 
  
  // show the alert (either success or fail)
  var $form_opener = $("#new_object_opener");
   
  <% if (not @object.errors.any?  ) and  
        (not @object.concept.nil?)  and  
        (@object.concept.length !=  0  )  %> 
    <% alert = escape_javascript(render :partial => "layouts/alert", :locals => {
      :success => true , 
      :text => "Project's  concept is successfully updated."
    }) %>
    
    <% content = escape_javascript(render :partial => "projects/job_requests/concept_planning/display", :locals => {
      :project => @object  
    }) %>
    
    
  //  hide the form 
    $form.hide(); 
    // $form.clearForm(); 
    
   // show the just-created concept 
    if( $alert.length >  0   ){
      $alert.after('<%= content %>'); 
    }else{
      $form_opener.after('<%= content %>'); 
      
    }
    
   
   // remove the no object list notification 
   $("#no_object_list").remove(); 
  
  <% else %>
   
    <% alert = escape_javascript(render :partial => "layouts/alert", :locals => {
      :success => false , 
      :text => "Update Concept Failed."
    }) %> 
    $form.show(); 
  <% end %>
  
  if( $("#alert").length == 0 ){
    $("#new_object_opener").after('<%= alert %>');
  }else{
    $("#alert").replaceWith('<%= alert %>');
  }
  
  
  
  $(".datepicker").datepicker({
    format: 'dd/mm/yyyy',
    autoclose : true 
  });
  
  $('.wysihtml5_textarea').wysihtml5({
  	"html": false, //Button which allows you to edit the generated HTML. Default false
  	"image": false //Button to insert an image. Default true
  });
   
  
  
});