config/routes.rb
Projectcamp::Application.routes.draw do
  devise_for :users

  root to: "bookings#public_index"
  resources :bookings 

  resources :pages, only: [:show, :index]

  get "sessions/login", to: "sessions#login", as: :login
  get "sessions/register", to: "sessions#register", as: :register
  
  
  match 'send_booking_ready_notification' => 'bookings#send_booking_ready_notification', :as => :send_booking_ready_notification, :method => :post 
  match 'close_booking' => 'bookings#close_booking', :as => :close_booking, :method => :post 
  match 'cancel_booking' => 'bookings#cancel_booking', :as => :cancel_booking, :method => :post 
  
  match 'refresh_booking_queue_row' => 'bookings#refresh_booking_queue_row', :as => :refresh_booking_queue_row, :method => :post 
  match 'refresh_public_booking_queue_row' => 'bookings#refresh_public_booking_queue_row', :as => :refresh_public_booking_queue_row, :method => :post 
  
  
  resources :projects   do
    resources :project_memberships 
    resources :deliverable_items 
  end
  
  resources :packages  do
    resources :deliverable_subcriptions  
  end
  
  resources :deliverables do
    resources :deliverable_components 
  end
  
  resources :deliverable_component_subcriptions do
    resources :drafts 
  end
  
  resources :job_requests 
  
=begin
  SETUP, Create User +  Office Role
=end

  match 'new_employee_creation' => "offices#new_employee_creation", :as => :new_employee_creation
  match 'create_employee' => "offices#create_employee" , :as => :create_employee, :method => :post 
  match 'show_role_for_employee/:employee_id' => "offices#show_role_for_employee" , :as => :show_role_for_employee
  match 'assign_role_for_employee' => "offices#assign_role_for_employee" , :as => :assign_role_for_employee, :method => :post

=begin
  Assigning project membership for employee
=end

  match 'assign_project_membership_role_for/:project_id' => "project_memberships#assign_project_membership_role_for",  :as => :assign_project_membership_role_for, :method => :post
  match 'finalize_membership_assignment' => "projects#finalize_membership_assignment",  :as => :finalize_membership_assignment, :method => :post 
  
=begin
  PRODUCTION MANAGEMENT 
=end

  match 'project_deliverable_items_production_overview/:project_id' => 'deliverable_items#project_deliverable_items_production_overview', :as => :project_deliverable_items_production_overview
  
  
  
=begin 
  JOB REQUEST FULFILLMENT  JOB_REQUEST_SOURCE[:assign_project_membership]
=end
  match 'task_based_project_membership_assignment/:job_request_id/for/:project_id' => "project_memberships#task_based_project_membership_assignment", :as => :task_based_project_membership_assignment
 
  
=begin 
  JOB REQUEST FULFILLMENT  JOB_REQUEST_SOURCE[:concept_planning]
=end
  match 'project_based_concept_planning_fulfillment/:project_id' => "projects#project_based_concept_planning_fulfillment", :as => :project_based_concept_planning_fulfillment
  match 'concept_planning_fulfillment/:job_request_id/for/:project_id' => "projects#concept_planning_fulfillment", :as => :concept_planning_fulfillment
  match 'update_project_concept/:project_id' => "projects#update_project_concept", :as => :update_project_concept, :method => :post 
  match 'finalize_concept' => 'projects#finalize_concept', :as => :finalize_concept, :method => :post 
  
=begin 
  JOB REQUEST FULFILLMENT  JOB_REQUEST_SOURCE[:shoot]
=end
  match 'project_based_shoot_finalization/:project_id' => "projects#project_based_shoot_finalization", :as => :project_based_shoot_finalization
  match 'shoot_finalization/:job_request_id/for/:project_id' => "projects#shoot_finalization", :as => :shoot_finalization
  match 'update_shoot_data/:project_id' => "projects#update_shoot_data", :as => :update_shoot_data, :method => :post
  match 'finalize_shoot_data' => 'projects#finalize_shoot_data', :as => :finalize_shoot_data, :method => :post 
  
=begin
  JOB REQUEST: Start Production
=end
  match 'task_based_deliverable_items_progress/:project_id' => "deliverable_items#task_based_deliverable_items_progress", :as => :task_based_deliverable_items_progress
  match 'task_based_draft_creation_for_component/:deliverable_component_subcription_id' => "drafts#task_based_draft_creation_for_component", :as => :task_based_draft_creation_for_component
  
  match 'task_based_production_team_assignment/:job_request_id/for/:project_id' => 'drafts#task_based_production_team_assignment', :as => :task_based_production_team_assignment
  
=begin
  DRAFT PRODUCTION, not from task 
=end
  match 'production_team_assignment/:draft_id' => 'drafts#production_team_assignment', :as => :production_team_assignment 
  match 'execute_production_team_assignment/:draft_id' => 'drafts#execute_production_team_assignment', :as => :execute_production_team_assignment, :method => :post 
  match 'finalize_production_team_assignment' => 'drafts#finalize_production_team_assignment', :as =>  :finalize_production_team_assignment, :method => :post 
  match 'internal_qc_deadline_assignment/:draft_id' => "drafts#internal_qc_deadline_assignment", :as => :internal_qc_deadline_assignment
  match 'execute_internal_qc_deadline_assignment/:draft_id' => 'drafts#execute_internal_qc_deadline_assignment', :as => :execute_internal_qc_deadline_assignment, :method => :post 
  
end

app/controllers/drafts_controller.rb
class DraftsController < ApplicationController
  def index
    setup_index
    
    add_breadcrumb "Project Management", 'projects_url'
    set_breadcrumb_for @project, 'project_deliverable_items_production_overview_url' + "(#{@project.id})", 
          "Production Management" 
    set_breadcrumb_for @deliverable_component_subcription, 'deliverable_component_subcription_drafts_url' + "(#{@deliverable_component_subcription.id})", 
          "Component: #{@deliverable_component.name}" 
  end
  
  def create
    @deliverable_component_subcription = 
      DeliverableComponentSubcription.find_by_id params[:deliverable_component_subcription_id]
    @parent_object = @deliverable_component_subcription 
    @new_object =  Draft.create_child_object( current_user, @deliverable_component_subcription, params[:draft]) 
  end
  
  
  def task_based_draft_creation_for_component
    setup_index
    
    add_breadcrumb "Task Management", 'job_requests_url'
    set_breadcrumb_for @project, 'task_based_deliverable_items_progress_url' + "(#{@project.id})", 
          "Production Management"
    set_breadcrumb_for @deliverable_component_subcription, 'task_based_draft_creation_for_component_url' + "(#{@deliverable_component_subcription.id})", 
          "Component: #{@deliverable_component.name}"
  end
  
=begin
  Production TEAM Assignment 
=end
  
  def production_team_assignment
    setup_production_team_assignment
    
    add_breadcrumb "Project Management", 'projects_url'
    set_breadcrumb_for @project, 'project_deliverable_items_production_overview_url' + "(#{@project.id})", 
          "Production Management" 
    set_breadcrumb_for @deliverable_component_subcription, 'deliverable_component_subcription_drafts_url' + "(#{@deliverable_component_subcription.id})", 
          "Component: #{@deliverable_component.name}"
    set_breadcrumb_for @draft, 'production_team_assignment_url' + "(#{@draft.id})", 
          "Production Assignment"
          
    render :file => "drafts/production_assignment/production_team_assignment"
  end
  
  def execute_production_team_assignment
    @draft = Draft.find_by_id params[:draft_id]
    @new_object = @draft.create_production_assignment( current_user, params[:job_request]  )
    
    render :file =>"drafts/production_assignment/execute_production_team_assignment" 
  end
  
  def task_based_production_team_assignment
    @job_request = JobRequest.find_by_id params[:job_request_id]
    @project = @job_request.project 
    @draft = @job_request.draft 
    
    @production_job_requests = @draft.job_requests.where(:job_request_source => JOB_REQUEST_SOURCE[:production_execution]).order("created_at DESC")
    
    add_breadcrumb "Task Management", 'job_requests_url'
    set_breadcrumb_for @project, 'task_based_production_team_assignment_url' + "(#{@job_request.id}, #{@project.id})", 
          "Production Management: Task Assignment"
          
    render :file => "drafts/production_assignment/task_based_production_team_assignment"
  end
  
  def finalize_production_team_assignment
    @draft = Draft.find_by_id params[:entity_id]
    @draft.finalize_production_team_assignment(current_user) 
    
    render :file => "drafts/production_assignment/finalize_production_team_assignment"
  end
  
=begin
  INTERNAL QC DEADLINE 
=end
  def internal_qc_deadline_assignment
    setup_internal_qc_deadline_assignment 
    
    add_breadcrumb "Project Management", 'projects_url'
    set_breadcrumb_for @project, 'project_deliverable_items_production_overview_url' + "(#{@project.id})", 
          "Production Management" 
    set_breadcrumb_for @deliverable_component_subcription, 'deliverable_component_subcription_drafts_url' + "(#{@deliverable_component_subcription.id})", 
          "Component: #{@deliverable_component.name}"
    set_breadcrumb_for @draft, 'internal_qc_deadline_assignment_url' + "(#{@draft.id})", 
          "QC Deadline Assignment"
          
    render :file => "drafts/qc_deadline/internal_qc_deadline_assignment"
    
    
  end
  
  
  
  def execute_internal_qc_deadline_assignment
    @draft = Draft.find_by_id params[:draft_id]
    @draft.update_internal_qc_deadline(current_user, params[:draft] )
    @draft.reload 
    @object = @draft
    
    render :file =>"drafts/qc_deadline/execute_internal_qc_deadline_assignment" 
  end
=begin
  PROTECTED ZONE 
=end
  
  protected
  
  def setup_internal_qc_deadline_assignment
    @draft = Draft.find_by_id params[:draft_id]
    @deliverable_component_subcription = @draft.deliverable_component_subcription
    @deliverable_component = @deliverable_component_subcription.deliverable_component 
    @project = @deliverable_component_subcription.project
  end
  
  def setup_production_team_assignment
    @draft = Draft.find_by_id params[:draft_id]
    @deliverable_component_subcription = @draft.deliverable_component_subcription
    @deliverable_component = @deliverable_component_subcription.deliverable_component 
    @project = @deliverable_component_subcription.project
    @job_requests = @draft.production_job_requests 
    @new_object = JobRequest.new 
  end
  
  
  def setup_index
    @deliverable_component_subcription = 
      DeliverableComponentSubcription.find_by_id params[:deliverable_component_subcription_id]
    @project = @deliverable_component_subcription.project
    
    @deliverable_item = @deliverable_component_subcription.deliverable_item
    @deliverable_component = @deliverable_component_subcription.deliverable_component
    @drafts = @deliverable_component_subcription.drafts.order("created_at ASC") 
    @last_draft = @deliverable_component_subcription.last_draft 
    
    @new_draft = Draft.new
  end
end

app/helpers/drafts_helper.rb
module DraftsHelper
end

app/views/drafts/production_assignment/_finalize_scheduling.html.erb
<%= simple_form_for( draft, :url => finalize_production_team_assignment_url,
      :method => :post , 
      :html => {:class => "form-horizontal prevent_double_submit ajax-form" ,
        :id => "finalizer"}) do |f| %>

 
        <%= hidden_field_tag 'entity_id' , draft.id  %>
  <div class="form-actions">
    <%= f.button :submit , :class => "btn green", :value=> "Finalize Production Scheduling" %>
  </div>
<% end %>

app/views/drafts/production_assignment/_new_object_form.html.erb
<%= simple_form_for( new_object, :url => url,
      :method => :post , 
      :html => {:class => "form-horizontal prevent_double_submit ajax-form   no_content_form",
        :id => "new_object"}) do |f| %>

  <%= f.input :description  , :input_html => {:class => "input-xlarge span5 wysihtml5_textarea" , :rows => 5  }, 
  :label => "Task Description" %>
  
  <%= f.input :user_id, :hint => "Select Employee", :label => "Target Employee" do %>
     <%= f.select :user_id, 
         User.all_selectable_employee %>
   <% end %>
   
   
   <hr />

  <%= f.input :start_date , :as => :string, 
    :input_html => {:class => "input-xlarge datepicker span5", :rows => 5,
      :value => format_date_from_datetime( new_object.start_date)}, 
    :label => "Start Date", :hint => "(format: dd/mm/yyyy)"   %>
    
  <%= f.input :deadline_date , :as => :string, 
    :input_html => {:class => "input-xlarge datepicker span5", :rows => 5,
      :value => format_date_from_datetime( new_object.deadline_date)}, 
    :label => "Deadline", :hint => "(format: dd/mm/yyyy)"   %>
    
  

  <div class="form-actions">
    <%= f.button :submit , :class => "btn btn-primary", :value=> "Create Assignment" %>
  </div>
<% end %>

app/views/drafts/production_assignment/_object_list_entry.html.erb
<tr id="object_list_entry-<%= object.id %>"> 
  <td><%= object.user.name %></td>
  <td><%= object.description.html_safe %></td>
  <td><%= format_date_from_datetime( object.start_date)  %></td>
  <td><%= format_date_from_datetime( object.deadline_date)  %></td>
</tr>

app/views/drafts/production_assignment/_scheduling_finalized.html.erb
<div class="alert alert-success finalize">
  <i class="icon-ok-sign"></i> Finalized
</div>

app/views/drafts/production_assignment/execute_production_team_assignment.js.erb
$(document).ready(function(){
  var $form = $("#new_object");  
  <% new_form = escape_javascript(  render :partial => "drafts/production_assignment/new_object_form", :locals => {
            :new_object => @new_object,
            :url => execute_production_team_assignment_url(@draft)  
          }) %>
  
  //  hide showLoading 
  $form.hideLoading();  
  $form.replaceWith('<%= new_form %>');  
  var $form = $("#new_object");  
  
  // show the alert (either success or fail)
  var $form_opener = $("#new_object_opener");
   
  <% if @new_object.persisted? %>
  // show notification that it is persisted
    <% alert = escape_javascript(render :partial => "layouts/alert", :locals => {
      :success => true , 
      :text => "Task for #{@new_object.user.name} is successfully created."
    }) %>
  //  hide the form 
    $form.hide(); 
    $form.clearForm(); 
  // add the entry into the table 
  
    <% new_row = escape_javascript(  render :partial => "drafts/production_assignment/object_list_entry", :locals => { 
              :object => @new_object
            }) %>
          
    $("#object_list").prepend('<%= new_row %>');
  
    // show the table (if it is the first viewable object)
    $("#object_list").removeClass("<%= HIDE_TABLE %>")
    $("#no_object_list").remove();
  
  <% else %>
    <% alert = escape_javascript(render :partial => "layouts/alert", :locals => {
      :success => false , 
      :text => "Task Creation Failed."
    }) %> 
    $form.show(); 
  <% end %>
  
  if( $("#alert").length == 0 ){
    $("#new_object_opener").after('<%= alert %>');
  }else{
    $("#alert").replaceWith('<%= alert %>');
  }
  
  
  
  $(".datepicker").datepicker({
    format: 'dd/mm/yyyy',
    autoclose : true 
  });
  
  $('.wysihtml5_textarea').wysihtml5({
  	"html": false, //Button which allows you to edit the generated HTML. Default false
  	"image": false //Button to insert an image. Default true
  });
   
  
  
});

app/views/drafts/production_assignment/finalize_production_team_assignment.js.erb
$(document).ready(function(){
  
  
  $("#finalizer").hideLoading();
  <% if @draft.is_production_scheduling_finalized == true %>
    <% new_notification = escape_javascript(render :partial => "drafts/production_assignment/scheduling_finalized", 
      :locals => {
      :draft => @draft 
    }) %>
    
    $("#finalizer").replaceWith('<%= new_notification %>' );
  <% else %>
   
    <% new_form = escape_javascript(render :partial => "drafts/production_assignment/finalize_scheduling", 
      :locals => {
      :draft => @draft 
    }) %>
    
    $("#finalizer").replaceWith('<%= new_form %>' );
  <% end %>
  
});

app/views/drafts/production_assignment/production_team_assignment.html.erb
<% if params[:action] =='production_team_assignment'%>
  <% content_for :additional_mini_app_nav do %>
    <%= render :partial => 'layouts/mini_app_nav' %>
  <% end %>
<% end %>


<% content_for :additional_js do %>
  <%= javascript_include_tag "project_summary", "wysihtml5-0.3.0_rc2.min", "bootstrap-wysihtml5-0.0.2.min" %>
  <script type="text/javascript">
    $(document).ready(function(){
      $('.wysihtml5_textarea').wysihtml5({
      	"html": false, //Button which allows you to edit the generated HTML. Default false
      	"image": false //Button to insert an image. Default true
      }); 
    });
  </script>
<% end %>

<% content_for :additional_css do %>
  <%= stylesheet_link_tag "bootstrap-wysihtml5-0.0.2" %>
<% end %>






<div class="padded">
  
  
  <% if @draft.is_production_scheduling_finalized == true %>
     <%= render :partial => "drafts/production_assignment/scheduling_finalized", :locals => {
       :draft => @draft 
     }%>
   <% else %>
     <%= render :partial => "drafts/production_assignment/finalize_scheduling", :locals => {
       :draft => @draft 
     }%>
   <% end %>
   
   
  
  <% if  current_user.has_project_role_symbol?(@project, :project_manager) %>
    <%= render :partial => "layouts/new_object_opener", :locals => {
      :text => "New Assignment"
    } %>
  <% end %>
  
  
   
  <% if @job_requests.length == 0 %>
    <%= render :partial => "layouts/no_object_list", :locals => {
      :objects => "assignments",
      :single_object => "assignment" , 
      :subject => "draft"
    } %>
  <% end %>
   
   
  <% if current_user.has_project_role_symbol?(@project, :project_manager) %>
    <%= render :partial => "drafts/production_assignment/new_object_form", :locals => {
      :new_object => @new_object,
      :url => execute_production_team_assignment_url(@draft)  
    }%>
  <% end %>
 
 
 
  
  
  
    
    <table class="table table-bordered table-striped table-header <%= show_table?( @job_requests )%>" id="object_list">
      <thead>
        <tr>
          <th>Employee</th>
          <th>Description</th>
          <th>Start</th>
          <th>Deadline</th> 
        </tr>
      </thead>
      <tbody id="package_list">
        <% @job_requests.each do |job_request| %>
          <%= render :partial => "drafts/production_assignment/object_list_entry", :locals => {
            :object => job_request 
          }%>
        
        <% end %> 
      </tbody>
    </table>
</div>

app/views/drafts/production_assignment/task_based_production_team_assignment.html.erb
<div class="padded">
  
  
  <% if  current_user.has_role?(:head_project_manager)%>
    <%= render :partial => "layouts/new_object_opener", :locals => {
      :text => "New Production Assignment"
    } %>
  <% end %>
  
  
   
  <% if @production_job_requests.length == 0 %>
    <%= render :partial => "layouts/no_object_list", :locals => {
      :objects => "production assignments",
      :single_object => "production assignment" , 
      :subject => "draft"
    } %>
  <% end %>
   
   
  <%# if  current_user.has_role?(:head_project_manager)%>
    <%#= render :partial => "projects/new_object_form", :locals => {
      :new_object => @new_project,
      :url => projects_url  
    }%>
  <%# end %>
 
 
 
  
  
  
    
    <table class="table table-bordered table-striped table-header <%#= show_table?( @production_job_requests )%>" id="object_list">
      <thead>
        <tr>
          <th>Title</th>
          <th>Deadline</th>
          <th>Deliverables</th>
          <th>Membership</th>
          <th>Concept</th> 
          <th>Shoot Data</th> 
          <th>Production</th>
          <th>Post Production</th>
        </tr>
      </thead>
      <tbody id="package_list">
        <%# @projects.each do |project| %>
          <%#= render :partial => "projects/object_list_entry", :locals => {
            :object => project 
          }%>
        
        <%# end %> 
      </tbody>
    </table>
</div>